# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Agent-1

    steps:
    - name: checkout code
    - uses: actions/checkout@v4
    - name: Use Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: "23"
    - name: Frontend Complilation
      run :  |
        cd cilent
        find . -name "*.js" -exec node --check {} +

    - name: Backend Complilation
      run : |
        cd api
        find . -name "*.js" -exec node --check {} +
