name: Node.js CICD2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Agent-1   # make sure this runner actually exists!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Frontend Compilation
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +
